// <auto-generated />
using System;
using EnvimixWebAPI;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace EnvimixWebAPI.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20251228233313_RemoveIndex")]
    partial class RemoveIndex
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("EnvimixWebAPI.Entities.CarEntity", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(16)
                        .HasColumnType("varchar(16)");

                    b.HasKey("Id");

                    b.ToTable("Cars");
                });

            modelBuilder.Entity("EnvimixWebAPI.Entities.CheckpointEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<float>("Distance")
                        .HasColumnType("float");

                    b.Property<int>("NbRespawns")
                        .HasColumnType("int");

                    b.Property<int>("RecordId")
                        .HasColumnType("int");

                    b.Property<int>("Score")
                        .HasColumnType("int");

                    b.Property<float>("Speed")
                        .HasColumnType("float");

                    b.Property<int>("Time")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("RecordId");

                    b.ToTable("Checkpoints");
                });

            modelBuilder.Entity("EnvimixWebAPI.Entities.DiscordUserEntity", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(16)
                        .HasColumnType("varchar(16)");

                    b.Property<string>("AvatarHash")
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)");

                    b.Property<string>("Nickname")
                        .HasMaxLength(32)
                        .HasColumnType("varchar(32)");

                    b.Property<string>("Username")
                        .HasMaxLength(32)
                        .HasColumnType("varchar(32)");

                    b.HasKey("Id");

                    b.ToTable("DiscordUsers");
                });

            modelBuilder.Entity("EnvimixWebAPI.Entities.EnvimaniaSessionEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<DateTimeOffset>("EndedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<bool>("FinishedGracefully")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("MapId")
                        .HasColumnType("varchar(34)");

                    b.Property<string>("ServerId")
                        .HasColumnType("varchar(64)");

                    b.Property<DateTimeOffset>("StartedAt")
                        .HasColumnType("datetime(6)");

                    b.HasKey("Id");

                    b.HasIndex("MapId");

                    b.HasIndex("ServerId");

                    b.ToTable("EnvimaniaSessions");
                });

            modelBuilder.Entity("EnvimixWebAPI.Entities.GhostEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<byte[]>("Data")
                        .IsRequired()
                        .HasColumnType("longblob");

                    b.Property<DateTimeOffset>("LastModifiedAt")
                        .HasColumnType("datetime(6)");

                    b.HasKey("Id");

                    b.ToTable("Ghosts");
                });

            modelBuilder.Entity("EnvimixWebAPI.Entities.MapEntity", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(34)
                        .HasColumnType("varchar(34)");

                    b.Property<string>("Collection")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("varchar(64)");

                    b.Property<string>("FirstAppearedOnServerId")
                        .HasColumnType("varchar(64)");

                    b.Property<bool>("IsCampaignMap")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)");

                    b.Property<int?>("Order")
                        .HasColumnType("int");

                    b.Property<string>("TitlePackId")
                        .HasColumnType("varchar(64)");

                    b.HasKey("Id");

                    b.HasIndex("FirstAppearedOnServerId");

                    b.HasIndex("TitlePackId");

                    b.ToTable("Maps");
                });

            modelBuilder.Entity("EnvimixWebAPI.Entities.MapVisitEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("MapId")
                        .IsRequired()
                        .HasColumnType("varchar(34)");

                    b.Property<string>("UserId")
                        .HasColumnType("varchar(64)");

                    b.Property<DateTimeOffset>("VisitedAt")
                        .HasColumnType("datetime(6)");

                    b.HasKey("Id");

                    b.HasIndex("MapId");

                    b.HasIndex("UserId");

                    b.ToTable("MapVisits");
                });

            modelBuilder.Entity("EnvimixWebAPI.Entities.RatingEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("CarId")
                        .IsRequired()
                        .HasColumnType("varchar(16)");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<float?>("Difficulty")
                        .HasColumnType("float");

                    b.Property<int>("Gravity")
                        .HasColumnType("int");

                    b.Property<string>("MapId")
                        .IsRequired()
                        .HasColumnType("varchar(34)");

                    b.Property<float?>("Quality")
                        .HasColumnType("float");

                    b.Property<string>("ServerId")
                        .HasColumnType("varchar(64)");

                    b.Property<DateTimeOffset?>("UpdatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("UserId")
                        .HasColumnType("varchar(64)");

                    b.HasKey("Id");

                    b.HasIndex("CarId");

                    b.HasIndex("MapId");

                    b.HasIndex("ServerId");

                    b.HasIndex("UserId");

                    b.ToTable("Ratings");
                });

            modelBuilder.Entity("EnvimixWebAPI.Entities.RecordEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("CarId")
                        .IsRequired()
                        .HasColumnType("varchar(16)");

                    b.Property<DateTimeOffset>("DrivenAt")
                        .HasColumnType("datetime(6)");

                    b.Property<Guid?>("GhostId")
                        .HasColumnType("char(36)");

                    b.Property<int>("Gravity")
                        .HasColumnType("int");

                    b.Property<int>("Laps")
                        .HasColumnType("int");

                    b.Property<string>("MapId")
                        .IsRequired()
                        .HasColumnType("varchar(34)");

                    b.Property<int>("NbRespawns")
                        .HasColumnType("int");

                    b.Property<bool>("Restored")
                        .HasColumnType("tinyint(1)");

                    b.Property<int>("Score")
                        .HasColumnType("int");

                    b.Property<DateTimeOffset?>("ServersideDrivenAt")
                        .HasColumnType("datetime(6)");

                    b.Property<Guid?>("SessionId")
                        .HasColumnType("char(36)");

                    b.Property<int>("Time")
                        .HasColumnType("int");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("varchar(64)");

                    b.HasKey("Id");

                    b.HasIndex("CarId");

                    b.HasIndex("GhostId");

                    b.HasIndex("Gravity");

                    b.HasIndex("Laps");

                    b.HasIndex("MapId");

                    b.HasIndex("SessionId");

                    b.HasIndex("UserId");

                    b.HasIndex("UserId", "MapId", "CarId", "Gravity", "Laps", "Time", "DrivenAt");

                    b.ToTable("Records");
                });

            modelBuilder.Entity("EnvimixWebAPI.Entities.ServerEntity", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(64)
                        .HasColumnType("varchar(64)");

                    b.Property<string>("BanReason")
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)");

                    b.HasKey("Id");

                    b.ToTable("Servers");
                });

            modelBuilder.Entity("EnvimixWebAPI.Entities.StarEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("CarId")
                        .IsRequired()
                        .HasColumnType("varchar(16)");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("Gravity")
                        .HasColumnType("int");

                    b.Property<string>("MapId")
                        .IsRequired()
                        .HasColumnType("varchar(34)");

                    b.Property<string>("UserId")
                        .HasColumnType("varchar(64)");

                    b.HasKey("Id");

                    b.HasIndex("CarId");

                    b.HasIndex("MapId");

                    b.HasIndex("UserId");

                    b.ToTable("Stars");
                });

            modelBuilder.Entity("EnvimixWebAPI.Entities.TitleEntity", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(64)
                        .HasColumnType("varchar(64)");

                    b.Property<string>("DisplayName")
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)");

                    b.Property<string>("Key")
                        .HasMaxLength(64)
                        .HasColumnType("varchar(64)");

                    b.Property<DateTimeOffset?>("ReleasedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Version")
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)");

                    b.HasKey("Id");

                    b.ToTable("Titles");
                });

            modelBuilder.Entity("EnvimixWebAPI.Entities.UserEntity", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(64)
                        .HasColumnType("varchar(64)");

                    b.Property<string>("AvatarUrl")
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)");

                    b.Property<string>("BanReason")
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)");

                    b.PrimitiveCollection<string>("Color")
                        .HasColumnType("longtext");

                    b.Property<DateTimeOffset?>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Description")
                        .HasMaxLength(32767)
                        .HasColumnType("longtext");

                    b.Property<string>("DiscordUserId")
                        .HasColumnType("varchar(16)");

                    b.Property<int?>("FameStars")
                        .HasColumnType("int");

                    b.Property<bool>("Interested")
                        .HasColumnType("tinyint(1)");

                    b.Property<bool>("IsAdmin")
                        .HasColumnType("tinyint(1)");

                    b.Property<bool>("IsInsider")
                        .HasColumnType("tinyint(1)");

                    b.Property<float?>("LadderPoints")
                        .HasColumnType("float");

                    b.Property<string>("Language")
                        .HasMaxLength(64)
                        .HasColumnType("varchar(64)");

                    b.Property<string>("Nickname")
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)");

                    b.Property<string>("SteamUserId")
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)");

                    b.Property<Guid?>("TokenId")
                        .HasColumnType("char(36)");

                    b.Property<DateTimeOffset?>("UpdatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<int?>("ZoneId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("DiscordUserId");

                    b.HasIndex("ZoneId");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("EnvimixWebAPI.Entities.ValidationDiscordMessageEntity", b =>
                {
                    b.Property<ulong>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint unsigned");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<ulong>("Id"));

                    b.Property<int?>("RecordId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("RecordId");

                    b.ToTable("ValidationDiscordMessages");
                });

            modelBuilder.Entity("EnvimixWebAPI.Entities.ZoneEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)");

                    b.HasKey("Id");

                    b.ToTable("Zones");
                });

            modelBuilder.Entity("EnvimixWebAPI.Entities.CheckpointEntity", b =>
                {
                    b.HasOne("EnvimixWebAPI.Entities.RecordEntity", "Record")
                        .WithMany("Checkpoints")
                        .HasForeignKey("RecordId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Record");
                });

            modelBuilder.Entity("EnvimixWebAPI.Entities.EnvimaniaSessionEntity", b =>
                {
                    b.HasOne("EnvimixWebAPI.Entities.MapEntity", "Map")
                        .WithMany()
                        .HasForeignKey("MapId");

                    b.HasOne("EnvimixWebAPI.Entities.ServerEntity", "Server")
                        .WithMany("EnvimaniaSessions")
                        .HasForeignKey("ServerId");

                    b.Navigation("Map");

                    b.Navigation("Server");
                });

            modelBuilder.Entity("EnvimixWebAPI.Entities.MapEntity", b =>
                {
                    b.HasOne("EnvimixWebAPI.Entities.ServerEntity", "FirstAppearedOnServer")
                        .WithMany()
                        .HasForeignKey("FirstAppearedOnServerId");

                    b.HasOne("EnvimixWebAPI.Entities.TitleEntity", "TitlePack")
                        .WithMany()
                        .HasForeignKey("TitlePackId");

                    b.Navigation("FirstAppearedOnServer");

                    b.Navigation("TitlePack");
                });

            modelBuilder.Entity("EnvimixWebAPI.Entities.MapVisitEntity", b =>
                {
                    b.HasOne("EnvimixWebAPI.Entities.MapEntity", "Map")
                        .WithMany()
                        .HasForeignKey("MapId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("EnvimixWebAPI.Entities.UserEntity", "User")
                        .WithMany()
                        .HasForeignKey("UserId");

                    b.Navigation("Map");

                    b.Navigation("User");
                });

            modelBuilder.Entity("EnvimixWebAPI.Entities.RatingEntity", b =>
                {
                    b.HasOne("EnvimixWebAPI.Entities.CarEntity", "Car")
                        .WithMany()
                        .HasForeignKey("CarId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("EnvimixWebAPI.Entities.MapEntity", "Map")
                        .WithMany()
                        .HasForeignKey("MapId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("EnvimixWebAPI.Entities.ServerEntity", "Server")
                        .WithMany()
                        .HasForeignKey("ServerId");

                    b.HasOne("EnvimixWebAPI.Entities.UserEntity", "User")
                        .WithMany()
                        .HasForeignKey("UserId");

                    b.Navigation("Car");

                    b.Navigation("Map");

                    b.Navigation("Server");

                    b.Navigation("User");
                });

            modelBuilder.Entity("EnvimixWebAPI.Entities.RecordEntity", b =>
                {
                    b.HasOne("EnvimixWebAPI.Entities.CarEntity", "Car")
                        .WithMany()
                        .HasForeignKey("CarId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("EnvimixWebAPI.Entities.GhostEntity", "Ghost")
                        .WithMany()
                        .HasForeignKey("GhostId");

                    b.HasOne("EnvimixWebAPI.Entities.MapEntity", "Map")
                        .WithMany()
                        .HasForeignKey("MapId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("EnvimixWebAPI.Entities.EnvimaniaSessionEntity", "Session")
                        .WithMany()
                        .HasForeignKey("SessionId");

                    b.HasOne("EnvimixWebAPI.Entities.UserEntity", "User")
                        .WithMany("Records")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Car");

                    b.Navigation("Ghost");

                    b.Navigation("Map");

                    b.Navigation("Session");

                    b.Navigation("User");
                });

            modelBuilder.Entity("EnvimixWebAPI.Entities.StarEntity", b =>
                {
                    b.HasOne("EnvimixWebAPI.Entities.CarEntity", "Car")
                        .WithMany()
                        .HasForeignKey("CarId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("EnvimixWebAPI.Entities.MapEntity", "Map")
                        .WithMany()
                        .HasForeignKey("MapId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("EnvimixWebAPI.Entities.UserEntity", "User")
                        .WithMany()
                        .HasForeignKey("UserId");

                    b.Navigation("Car");

                    b.Navigation("Map");

                    b.Navigation("User");
                });

            modelBuilder.Entity("EnvimixWebAPI.Entities.UserEntity", b =>
                {
                    b.HasOne("EnvimixWebAPI.Entities.DiscordUserEntity", "DiscordUser")
                        .WithMany("Users")
                        .HasForeignKey("DiscordUserId");

                    b.HasOne("EnvimixWebAPI.Entities.ZoneEntity", "Zone")
                        .WithMany("Users")
                        .HasForeignKey("ZoneId");

                    b.Navigation("DiscordUser");

                    b.Navigation("Zone");
                });

            modelBuilder.Entity("EnvimixWebAPI.Entities.ValidationDiscordMessageEntity", b =>
                {
                    b.HasOne("EnvimixWebAPI.Entities.RecordEntity", "Record")
                        .WithMany()
                        .HasForeignKey("RecordId");

                    b.Navigation("Record");
                });

            modelBuilder.Entity("EnvimixWebAPI.Entities.DiscordUserEntity", b =>
                {
                    b.Navigation("Users");
                });

            modelBuilder.Entity("EnvimixWebAPI.Entities.RecordEntity", b =>
                {
                    b.Navigation("Checkpoints");
                });

            modelBuilder.Entity("EnvimixWebAPI.Entities.ServerEntity", b =>
                {
                    b.Navigation("EnvimaniaSessions");
                });

            modelBuilder.Entity("EnvimixWebAPI.Entities.UserEntity", b =>
                {
                    b.Navigation("Records");
                });

            modelBuilder.Entity("EnvimixWebAPI.Entities.ZoneEntity", b =>
                {
                    b.Navigation("Users");
                });
#pragma warning restore 612, 618
        }
    }
}
