services:
  envimix-webapi:
    build:
      context: .
      dockerfile: EnvimixWebAPI/Dockerfile
      target: final
    environment:
      ASPNETCORE_ENVIRONMENT: Development
      CONNECTIONSTRINGS__DEFAULTCONNECTION: Server=mariadb;Port=3306;Database=envimix;User=root;
      JWT__KEY: ${IDENTITY_JWT_KEY:-}
      MANIAPLANET__CLIENTID: ${MANIAPLANET_CLIENT_ID:-}
      MANIAPLANET__CLIENTSECRET: ${MANIAPLANET_CLIENT_SECRET:-}
      IDENTITYMANAGER: http://identity:8080
    ports:
      - 8080:8080
    depends_on:
      mariadb:
        condition: service_healthy
      identity:
        condition: service_started

  envimix-website:
    build:
      context: .
      dockerfile: EnvimixWebsite/EnvimixWebsite/Dockerfile
      target: final
    environment:
      ASPNETCORE_ENVIRONMENT: Development
      ENVIMIXAPI: http://envimix-webapi:8080
      IDENTITYMANAGER: http://identity:8080
      IDENTITYMANAGERPUBLIC: http://localhost:8082
    ports:
      - 8081:8080
    volumes:
      - identity-data-protection:/home/app/.aspnet/DataProtection-Keys
    depends_on:
      - envimix-webapi
      - identity

  identity:
    build:
      context: .
      dockerfile: Identity.Dockerfile
      target: final
    environment:
      ASPNETCORE_ENVIRONMENT: Development
      CONNECTIONSTRINGS__DEFAULTCONNECTION: Server=mariadb;Port=3306;Database=gbx_tools_identity;User=root;
      JWT__KEY: ${IDENTITY_JWT_KEY:-}
      MANIAPLANET__CLIENTID: ${MANIAPLANET_CLIENT_ID:-}
      MANIAPLANET__CLIENTSECRET: ${MANIAPLANET_CLIENT_SECRET:-}
      TRACKMANIA__CLIENTID: ${TRACKMANIA_CLIENT_ID:-}
      TRACKMANIA__CLIENTSECRET: ${TRACKMANIA_CLIENT_SECRET:-}
      DISCORD__CLIENTID: ${DISCORD_CLIENT_ID:-}
      DISCORD__CLIENTSECRET: ${DISCORD_CLIENT_SECRET:-}
      GITHUB__CLIENTID: ${GITHUB_CLIENT_ID:-}
      GITHUB__CLIENTSECRET: ${GITHUB_CLIENT_SECRET:-}
    ports:
      - 8082:8080
    volumes:
      - identity-data-protection:/home/app/.aspnet/DataProtection-Keys
    depends_on:
      mariadb:
        condition: service_healthy

#  envimix-discord-bot:
#    build:
#      context: .
#      dockerfile: EnvimixDiscordBot/Dockerfile
#      target: final
#    environment:
#      ASPNETCORE_ENVIRONMENT: Development
#      CONNECTIONSTRINGS__DEFAULTCONNECTION: Server=mariadb;Port=3306;Database=envimix_discord_bot;User=root;
#    depends_on:
#      mariadb:
#        condition: service_healthy
  
  mariadb:
    image: mariadb
    restart: unless-stopped
    command: --max_allowed_packet=32505856
    environment:
      TZ: CET
      MARIADB_ALLOW_EMPTY_ROOT_PASSWORD: 1
    healthcheck:
      test: ["CMD", "healthcheck.sh", "--connect", "--innodb_initialized"]
      start_period: 10s
      interval: 10s
      timeout: 5s
      retries: 3

  phpmyadmin:
    image: beeyev/phpmyadmin-lightweight
    restart: unless-stopped
    ports:
      - 9015:80
    environment:
      PMA_HOST: mariadb
      PMA_USER: root
    depends_on:
      mariadb:
        condition: service_healthy

volumes:
  identity-data-protection:

