// <auto-generated />
using System;
using EnvimixDiscordBot;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace EnvimixDiscordBot.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20250720013230_InitMariaDB")]
    partial class InitMariaDB
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.7")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("EnvimixDiscordBot.Models.CampaignModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("ClubId")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)");

                    b.Property<ulong?>("NewsChannelId")
                        .HasColumnType("bigint unsigned");

                    b.Property<ulong?>("NewsMessageId")
                        .HasColumnType("bigint unsigned");

                    b.Property<ulong?>("StatusChannelId")
                        .HasColumnType("bigint unsigned");

                    b.Property<ulong?>("StatusMessageId")
                        .HasColumnType("bigint unsigned");

                    b.Property<ulong?>("SubmitterId")
                        .HasColumnType("bigint unsigned");

                    b.HasKey("Id");

                    b.HasIndex("SubmitterId");

                    b.ToTable("Campaigns");
                });

            modelBuilder.Entity("EnvimixDiscordBot.Models.CarModel", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(16)
                        .HasColumnType("varchar(16)");

                    b.HasKey("Id");

                    b.ToTable("Cars");
                });

            modelBuilder.Entity("EnvimixDiscordBot.Models.ConvertedMapModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CampaignId")
                        .HasColumnType("int");

                    b.Property<string>("CarId")
                        .IsRequired()
                        .HasColumnType("varchar(16)");

                    b.Property<DateTimeOffset?>("ClaimedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<ulong?>("ClaimedById")
                        .HasColumnType("bigint unsigned");

                    b.Property<byte[]>("Data")
                        .IsRequired()
                        .HasColumnType("mediumblob");

                    b.Property<bool>("Impossible")
                        .HasColumnType("tinyint(1)");

                    b.Property<DateTimeOffset?>("LastModifiedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("varchar(64)");

                    b.Property<int>("Order")
                        .HasColumnType("int");

                    b.Property<string>("OriginalName")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)");

                    b.Property<string>("OriginalUid")
                        .IsRequired()
                        .HasMaxLength(36)
                        .HasColumnType("varchar(36)");

                    b.Property<string>("Uid")
                        .IsRequired()
                        .HasMaxLength(36)
                        .HasColumnType("varchar(36)");

                    b.Property<bool>("Validated")
                        .HasColumnType("tinyint(1)");

                    b.HasKey("Id");

                    b.HasIndex("CampaignId");

                    b.HasIndex("CarId");

                    b.HasIndex("ClaimedById");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.HasIndex("OriginalUid")
                        .IsUnique();

                    b.ToTable("ConvertedMaps");
                });

            modelBuilder.Entity("EnvimixDiscordBot.Models.UserModel", b =>
                {
                    b.Property<ulong>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint unsigned");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<ulong>("Id"));

                    b.HasKey("Id");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("EnvimixDiscordBot.Models.CampaignModel", b =>
                {
                    b.HasOne("EnvimixDiscordBot.Models.UserModel", "Submitter")
                        .WithMany()
                        .HasForeignKey("SubmitterId");

                    b.Navigation("Submitter");
                });

            modelBuilder.Entity("EnvimixDiscordBot.Models.ConvertedMapModel", b =>
                {
                    b.HasOne("EnvimixDiscordBot.Models.CampaignModel", "Campaign")
                        .WithMany("Maps")
                        .HasForeignKey("CampaignId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("EnvimixDiscordBot.Models.CarModel", "Car")
                        .WithMany()
                        .HasForeignKey("CarId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("EnvimixDiscordBot.Models.UserModel", "ClaimedBy")
                        .WithMany("Maps")
                        .HasForeignKey("ClaimedById");

                    b.Navigation("Campaign");

                    b.Navigation("Car");

                    b.Navigation("ClaimedBy");
                });

            modelBuilder.Entity("EnvimixDiscordBot.Models.CampaignModel", b =>
                {
                    b.Navigation("Maps");
                });

            modelBuilder.Entity("EnvimixDiscordBot.Models.UserModel", b =>
                {
                    b.Navigation("Maps");
                });
#pragma warning restore 612, 618
        }
    }
}
